version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          repo: ${ECR_REPOSITORY_NAME}
          region: AWS_REGION
          tag: ${CIRCLE_BUILD_NUM}

  update-deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Update deployment file
          command: |
            sed -i 's|image: .*|image: ${AWS_ACCOUNT_URL}/${ECR_REPOSITORY_NAME}:${CIRCLE_BUILD_NUM}|' manifists/deployment.yaml
      - run:
          name: Commit and push changes
          command: |
            git config user.email "ziyadtr101@gmail.com"
            git config user.name "ZeyadTareq224"
            git add manifists/deployment.yaml
            git commit -m "Update image tag to ${CIRCLE_BUILD_NUM}"
            git push origin ${CIRCLE_BRANCH}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-push
      - update-deployment:
          requires:
            - build-and-push